---
title: "Untitled"
format: html
---

```{r}
library(tidyverse)
library(lemon)
library(ggrain)
library(showtext)
library(ggtext)
library(ggrepel)
```

```{r}
font_add_google('Arimo', 'arimo')
showtext_auto()
```

```{r}
title <- 'How Nations Percevied Their Corruption'
subtitle <- 'For most nations, more than half of the population already believes that corruption exists. The distributions reveal an \ninteresting pattern: Africa and Asia display a right-skewed shape with a few outliers, North America follows a very flat \nnormal distribution, and Europe — perceived as less corrupt than the rest of the world — exhibits a bimodal distribution.'
caption <- "Data: OurWorldInData | Vis:MhKirmizi"
```

```{r}
df <- read_csv('D:/VIS/data_makeovermonday/makeovermonday-corruption/data/ti_corruption_perception_index.csv')
```

```{r}
df_mean <- df |> 
    group_by(entity) |> 
    summarise(avg_corruption = mean(corruption_perceptions_index, na.rm = TRUE)) |> 
    drop_na() |> 
    arrange(-avg_corruption)
```

```{r}
df |> 
     drop_na(world_regions_according_to_owid) |> 
    drop_na(corruption_perceptions_index) |> 
    ggplot(aes(world_regions_according_to_owid, corruption_perceptions_index, fill = world_regions_according_to_owid)) +
    geom_rain(alpha = .6) +
    coord_flex_cart(bottom=brackets_horizontal()) + 
    paletteer::scale_fill_paletteer_d("Manu::Kakapo") +
    labs(x = '', y = 'Corruption Perception Index', title = title, subtitle = subtitle,caption = caption) +
    theme_classic(base_family = 'arimo', base_size = 14) +
    theme(
        legend.position = 'none', 
        plot.title = element_text(size = 36, hjust = .5, face = 'bold'),
        plot.subtitle = element_text(size = 20, hjust = .5),
        panel.grid.major.y = element_line(linetype = 'dashed'),

    )
```

```{r}
ggsave("corruption.png", width = 1920, height = 1080, units = "px", dpi = 132)
```
