---
title: "Untitled"
format: html
---
```{r}
library(tidyverse)
library(showtext)
library(hrbrthemes)
library(scales)
```

```{r}
### Subtitle 
subtitle <- 'While minimum wages have risen steadily in 10 EU countries since 2020, \nthe growth in Germany and Poland far outpaces that of others.'
```

```{r}
### Data sets 
df <- read_csv('Wages  - Sheet1.csv')
```

```{r}
class(df$Date)
unique(df$Date)
```

```{r}
df2 <- df |> 
  mutate(
    Date = as.Date(Date, format = "%d/%m/%Y"),
    year = lubridate::year(Date)
  ) |> 
  select(year, Belgium: Portugal) |> 
  filter(year %in% c(2020, 2025)) |> 
  pivot_longer(!year, names_to = 'country', values_to = 'wage')
```

```{r}
df2 |> 
  filter(year %in% c(2020, 2025)) |> 
  ggplot(aes(year, wage, group = country)) +
  geom_line(aes(color = if_else(country %in% c("Poland", "Germany"), country, "grey66")),
            alpha = 0.3, size = 1.5) +
  geom_point(aes(color = if_else(country %in% c("Poland", "Germany"), country, "grey66"),
                 size = wage)) +
  geom_text_repel(
    data = df2 |> filter(year == 2025),
    aes(label = country, color = country, hjust = .5),
    size = 6,
    nudge_x = .5,
    segment.color = NA
  ) +
  scale_color_manual(values = c("Poland" = "#BD5630FF", "Germany" = "#E5AD4FFF", "grey66" = "grey66")) +
  scale_x_continuous(breaks = c(2020, 2025), labels = c("2020", "2025")) +
  scale_y_continuous(breaks = seq(500, 2500, 500), labels = label_currency(prefix = "€", suffix = "")) +
  scale_size_continuous(range = c(2, 10)) +
  labs(
    x = "", 
    y = "Wage",  
    title = "It’s Not the Wage, but the Rise",
    subtitle = subtitle,
    caption = "Data: EU | Vis: MhKirmizi"
  ) +
  theme_ipsum_rc(base_size = 12, base_family = "PT Sans") +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 48, hjust = 0.5, 
    family = "PT Sans", face = "bold", color = "#121510FF"), 
    plot.subtitle = element_text(size = 24, hjust = .5, family = "PT Sans"),
    plot.caption = element_text(size = 14, family = "PT Sans"),
    axis.title.y = element_text(size =12, family = "PT Sans"),
    panel.grid.minor.y = element_blank(), 
    panel.grid.major.y = element_line(linetype = 'dashed'), 
    panel.grid.minor.x = element_blank(), 
    plot.background = element_rect(fill = 'white', color = 'white'), 
    panel.background = element_rect(fill = 'white', color = 'white')
  )

```

```{r}
ggsave("week31.png", width = 1920, height = 1080, units = "px", dpi = 132)
```